// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto.Infraestrutura.Data;

#nullable disable

namespace Projeto.Infraestrutura.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Projeto.RegrasDeNegocio.Models.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstadoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("Cidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstadoId = 1,
                            Nome = "São Paulo"
                        },
                        new
                        {
                            Id = 2,
                            EstadoId = 1,
                            Nome = "Campinas"
                        },
                        new
                        {
                            Id = 3,
                            EstadoId = 2,
                            Nome = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = 4,
                            EstadoId = 2,
                            Nome = "Niterói"
                        },
                        new
                        {
                            Id = 5,
                            EstadoId = 3,
                            Nome = "Belo Horizonte"
                        },
                        new
                        {
                            Id = 6,
                            EstadoId = 3,
                            Nome = "Uberlândia"
                        });
                });

            modelBuilder.Entity("Projeto.RegrasDeNegocio.Models.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Estados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "São Paulo",
                            UF = "SP"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Rio de Janeiro",
                            UF = "RJ"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Minas Gerais",
                            UF = "MG"
                        });
                });

            modelBuilder.Entity("Projeto.RegrasDeNegocio.Models.Cidade", b =>
                {
                    b.HasOne("Projeto.RegrasDeNegocio.Models.Estado", "Estado")
                        .WithMany("Cidades")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("Projeto.RegrasDeNegocio.Models.Estado", b =>
                {
                    b.Navigation("Cidades");
                });
#pragma warning restore 612, 618
        }
    }
}
